---
version: "3.8"
services:
  movies:
    image: veerperu1712/pmovies:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  train:
    image: veerperu1712/ptrain:latest
    ports:
      - 92:80
    deploy:
      replicas: 3
  recharge:
    image: veerperu1712/precharge:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: veerperu1712/pdth:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
